version: '3.9'

services:
    web:
        build:
            context: ./
            dockerfile: ./docker/dev/Dockerfile
        image: angular-app
        container_name: angular-app
        working_dir: /home/node/app
        volumes:
            - ./:/home/node/app
            - node_modules:/home/node/app/node_modules
        ports:
            - 8081:4200
        command: sh -c "npm start"
        restart: unless-stopped

volumes:
  node_modules: