version: '3.9'

services:
    web:
        build:
            context: ./
            dockerfile: ./docker/dev/Dockerfile
        image: angular-app
        container_name: angular-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - 8081:80
        restart: unless-stopped